Task-3.1
eduardo-neto-epam/nodejs-training pull request #7
Opened 2021-11-06 21:33 UTC by eduardo-neto-epam

- Added postgresql elephantSql DB;
- Added Sequelize ORM with migrations, seed files and config with sequilizerc;
- Added scripts to run sequelize cli commands;
- Updated code to work with new database.

2021-11-06 21:46 UTC, eduardo-neto-epam commented
@Dmitry-White 
Task 3.2 requests a patten that I already follow although I have more of a components approach. 
Do I need to change anything here or is it done already?

2021-11-17 17:01 UTC, Dmitry-White requested changes
Looks pretty solid, seems like you've got some experience already!

2021-11-17 17:01 UTC, Dmitry-White commented on src/user/user.controller.ts
> +            if (userId instanceof HttpException) {
Consider using "early-return" approach here.

2021-11-17 17:01 UTC, Dmitry-White commented on src/user/user.service.ts
> +            return user === null || user.getDataValue('isDeleted') ? new UserNotFoundException(id) : user;
Consider using "early-return" approach here.

2021-11-22 09:47 UTC, eduardo-neto-epam commented on src/database/config/database.config.ts
> +const db = new Sequelize(process.env.DB_URL as string, {
Thanks! :)

2021-11-22 14:08 UTC, Dmitry-White approved these changes
Looks great!

2021-11-24 12:47 UTC, merged